osx_image: xcode8.2
language: objective-c
script:
  - set -o pipefail && xcodebuild test -workspace Wolf.xcworkspace -scheme Wolf ONLY_ACTIVE_ARCH=NO -configuration Release
  - travis_wait 30 pod lib lint
  
